# Fiscal Digital — funding sources
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [fiscal-digital]
custom:
  - https://catarse.me/fiscaldigital
  - https://fiscaldigital.org/apoie
  - https://fiscaldigital.org/transparencia
